# SPEACH TO TEXT

In [1]:
%pip install faster-whisper

Collecting faster-whisper
  Downloading faster_whisper-1.2.1-py3-none-any.whl.metadata (16 kB)
Collecting ctranslate2<5,>=4.0 (from faster-whisper)
  Downloading ctranslate2-4.7.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting huggingface-hub>=0.21 (from faster-whisper)
  Downloading huggingface_hub-1.11.0-py3-none-any.whl.metadata (14 kB)
Collecting tokenizers<1,>=0.13 (from faster-whisper)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting onnxruntime<2,>=1.14 (from faster-whisper)
  Downloading onnxruntime-1.24.4-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Collecting av>=11 (from faster-whisper)
  Downloading av-17.0.1-cp311-abi3-manylinux_2_28_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: tqdm in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from faster-whisper) (4.67.3)
Requirement already satisfied: setuptools in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from ctranslate2<5,>=4.0->faster-whisper) (70.2.0)
Requirement already satisfied: numpy in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from ctranslate2<5,>=4.0->faster-whisper) (2.4.3)
Requirement already satisfied: pyyaml<7,>=5.3 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from ctranslate2<5,>=4.0->faster-whisper) (6.0.3)
Requirement already satisfied: flatbuffers in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from onnxruntime<2,>=1.14->faster-whisper) (25.12.19)
Requirement already satisfied: packaging in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from onnxruntime<2,>=1.14->faster-whisper) (26.0)
Requirement already satisfied: protobuf in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from onnxruntime<2,>=1.14->faster-whisper) (7.34.1)
Requirement already satisfied: sympy in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from onnxruntime<2,>=1.14->faster-whisper) (1.14.0)
Requirement already satisfied: filelock>=3.10.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from huggingface-hub>=0.21->faster-whisper) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from huggingface-hub>=0.21->faster-whisper) (2026.2.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub>=0.21->faster-whisper)
  Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from huggingface-hub>=0.21->faster-whisper) (0.28.1)
Collecting typer (from huggingface-hub>=0.21->faster-whisper)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from huggingface-hub>=0.21->faster-whisper) (4.15.0)
Requirement already satisfied: anyio in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21->faster-whisper) (4.13.0)
Requirement already satisfied: certifi in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21->faster-whisper) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21->faster-whisper) (1.0.9)
Requirement already satisfied: idna in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.21->faster-whisper) (3.11)
Requirement already satisfied: h11>=0.16 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.21->faster-whisper) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from sympy->onnxruntime<2,>=1.14->faster-whisper) (1.3.0)
Collecting click>=8.2.1 (from typer->huggingface-hub>=0.21->faster-whisper)
  Downloading click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub>=0.21->faster-whisper)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=12.3.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from typer->huggingface-hub>=0.21->faster-whisper) (14.3.3)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub>=0.21->faster-whisper)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.21->faster-whisper) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.21->faster-whisper) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.21->faster-whisper) (0.1.2)
Downloading faster_whisper-1.2.1-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 7.3 MB/s  0:00:00
Downloading ctranslate2-4.7.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (38.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.8/38.8 MB 10.2 MB/s  0:00:03m0:00:0100:01
Downloading onnxruntime-1.24.4-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (17.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 9.5 MB/s  0:00:01m eta 0:00:01
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 9.5 MB/s  0:00:00m eta 0:00:01
Downloading huggingface_hub-1.11.0-py3-none-any.whl (645 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 645.5/645.5 kB 7.9 MB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 9.7 MB/s  0:00:006m0:00:010:01
Downloading av-17.0.1-cp311-abi3-manylinux_2_28_x86_64.whl (36.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.3/36.3 MB 9.8 MB/s  0:00:036m0:00:0100:01
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.3.2-py3-none-any.whl (108 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: shellingham, hf-xet, ctranslate2, click, av, annotated-doc, onnxruntime, typer, huggingface-hub, tokenizers, faster-whisper
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/11 [faster-whisper]m [huggingface-hub]
Successfully installed annotated-doc-0.0.4 av-17.0.1 click-8.3.2 ctranslate2-4.7.1 faster-whisper-1.2.1 hf-xet-1.4.3 huggingface-hub-1.11.0 onnxruntime-1.24.4 shellingham-1.5.4 tokenizers-0.22.2 typer-0.24.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install streamlit duckdb plotly langchain langchain-openai langchain-experimental faster-whisper mutagen

Collecting streamlit
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Collecting duckdb
  Downloading duckdb-1.5.2-cp311-cp311-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (4.2 kB)
Collecting plotly
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Collecting langchain
  Downloading langchain-1.2.15-py3-none-any.whl.metadata (5.8 kB)
Collecting langchain-openai
  Downloading langchain_openai-1.1.14-py3-none-any.whl.metadata (3.1 kB)
Collecting langchain-experimental
  Downloading langchain_experimental-0.4.1-py3-none-any.whl.metadata (1.3 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.0.5-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (8.3.2)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<3,>=1.23 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (2.4.3)
Requirement already satisfied: packaging>=20 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (3.0.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (12.1.1)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (7.34.1)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-23.0.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: requests<3,>=2.27 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (2.33.1)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (6.5.5)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
Requirement already satisfied: jinja2 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.19.0-py3-none-any.whl.metadata (14 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Collecting langchain-core<2.0.0,>=1.2.10 (from langchain)
  Downloading langchain_core-1.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting langgraph<1.2.0,>=1.1.5 (from langchain)
  Downloading langgraph-1.1.8-py3-none-any.whl.metadata (8.0 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.13.2-py3-none-any.whl.metadata (108 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading langsmith-0.7.32-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (6.0.3)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading uuid_utils-0.14.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: jsonpointer>=1.9 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.1)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.2.0,>=1.1.5->langchain)
  Downloading langgraph_checkpoint-4.0.2-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.9 (from langgraph<1.2.0,>=1.1.5->langchain)
  Downloading langgraph_prebuilt-1.0.10-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.2.0,>=1.1.5->langchain)
  Downloading langgraph_sdk-0.3.13-py3-none-any.whl.metadata (1.6 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.2.0,>=1.1.5->langchain)
  Downloading xxhash-3.6.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain)
  Downloading ormsgpack-1.12.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Requirement already satisfied: httpx>=0.25.2 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (0.28.1)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain)
  Downloading orjson-3.11.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain)
  Downloading zstandard-0.25.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: anyio in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (4.13.0)
Requirement already satisfied: httpcore==1.* in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.2.0,>=1.1.5->langchain) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.46.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting openai<3.0.0,>=2.26.0 (from langchain-openai)
  Downloading openai-2.32.0-py3-none-any.whl.metadata (31 kB)
Collecting tiktoken<1.0.0,>=0.7.0 (from langchain-openai)
  Downloading tiktoken-0.12.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (6.7 kB)
Collecting distro<2,>=1.7.0 (from openai<3.0.0,>=2.26.0->langchain-openai)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting jiter<1,>=0.10.0 (from openai<3.0.0,>=2.26.0->langchain-openai)
  Downloading jiter-0.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Collecting sniffio (from openai<3.0.0,>=2.26.0->langchain-openai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>4 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai) (4.67.3)
Collecting regex>=2022.1.18 (from tiktoken<1.0.0,>=0.7.0->langchain-openai)
  Downloading regex-2026.4.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting langchain-community<1.0.0,>=0.4.0 (from langchain-experimental)
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading langchain_classic-1.0.4-py3-none-any.whl.metadata (4.8 kB)
Collecting SQLAlchemy<3.0.0,>=1.4.0 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading sqlalchemy-2.0.49-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading aiohttp-3.13.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading pydantic_settings-2.13.1-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (26.1.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading frozenlist-1.8.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading multidict-6.7.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading propcache-0.4.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading yarl-1.23.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.2.2)
Collecting greenlet>=1 (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading greenlet-3.4.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /home/raja/miniconda3/envs/predictive_env/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 14.9 MB/s  0:00:00 eta 0:00:01
Downloading altair-6.0.0-py3-none-any.whl (795 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 795.4/795.4 kB 12.5 MB/s  0:00:00
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-7.0.5-py3-none-any.whl (13 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 15.7 MB/s  0:00:00 eta 0:00:01
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl (79 kB)
Downloading duckdb-1.5.2-cp311-cp311-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (21.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.4/21.4 MB 12.4 MB/s  0:00:01m0:00:0100:01
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 9.0 MB/s  0:00:01 eta 0:00:01
Downloading langchain-1.2.15-py3-none-any.whl (112 kB)
Downloading langchain_core-1.3.0-py3-none-any.whl (515 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph-1.1.8-py3-none-any.whl (173 kB)
Downloading langgraph_checkpoint-4.0.2-py3-none-any.whl (51 kB)
Downloading langgraph_prebuilt-1.0.10-py3-none-any.whl (36 kB)
Downloading langgraph_sdk-0.3.13-py3-none-any.whl (96 kB)
Downloading langsmith-0.7.32-py3-none-any.whl (378 kB)
Downloading pydantic-2.13.2-py3-none-any.whl (471 kB)
Downloading pydantic_core-2.46.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.4 MB/s  0:00:00
Downloading uuid_utils-0.14.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (345 kB)
Downloading langchain_openai-1.1.14-py3-none-any.whl (88 kB)
Downloading openai-2.32.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 10.4 MB/s  0:00:00
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading jiter-0.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (358 kB)
Downloading tiktoken-0.12.0-cp311-cp311-manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 11.4 MB/s  0:00:00
Downloading langchain_experimental-0.4.1-py3-none-any.whl (210 kB)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 11.3 MB/s  0:00:00 eta 0:00:01
Downloading aiohttp-3.13.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 11.2 MB/s  0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.4-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 8.1 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
Downloading multidict-6.7.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (246 kB)
Downloading pydantic_settings-2.13.1-py3-none-any.whl (58 kB)
Downloading sqlalchemy-2.0.49-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 10.9 MB/s  0:00:00 eta 0:00:01
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading yarl-1.23.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (102 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading frozenlist-1.8.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (231 kB)
Downloading greenlet-3.4.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (613 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 613.5/613.5 kB 9.2 MB/s  0:00:00
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading narwhals-2.19.0-py3-none-any.whl (446 kB)
Downloading orjson-3.11.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (133 kB)
Downloading ormsgpack-1.12.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Downloading propcache-0.4.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (210 kB)
Downloading pyarrow-23.0.1-cp311-cp311-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 11.8 MB/s  0:00:04m0:00:0100:01
Downloading regex-2026.4.4-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (799 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 799.8/799.8 kB 10.5 MB/s  0:00:00
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)

In [1]:
import pandas as pd
import os
from faster_whisper import WhisperModel
from dotenv import load_dotenv

import file_manipulation as fm
import time

/home/raja/miniconda3/envs/chatbot_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [15]:
p = pd.read_parquet("data/labeled/labeled_complaints.parquet")
p.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company', 'State', 'Tags',
       'Company response to consumer', 'Consumer disputed?', 'clean_narrative',
       'word_count', 'lda_topic', 'lda_topic_label', 'bert_topic',
       'bert_topic_label', 'category', 'year_month', 'year', 'month',
       'date_dt', 'volume_score', 'growth_score', 'is_unresolved',
       'severity_score', 'recency_score', 'length_score', 'danger_boost',
       'priority_score', 'priority_tier'],
      dtype='str')

In [18]:
p.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company,State,Tags,Company response to consumer,...,date_dt,volume_score,growth_score,is_unresolved,severity_score,recency_score,length_score,danger_boost,priority_score,priority_tier
0,2024-01-28,Credit Reporting Or Other Personal Consumer Re...,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,Urgent : Disputed Inquiries on Credit Report -...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,NaN,Closed with explanation,...,2024-01-28,60.459203,17.581078,0,50.0,58.835868,46.2,0,33.0,Medium
1,2023-12-18,Credit Reporting Or Other Personal Consumer Re...,Credit reporting,Problem with a company's investigation into an...,Their investigation did not fix an error on yo...,I am writing to address a matter that has been...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",FL,NaN,Closed with non-monetary relief,...,2023-12-18,60.459203,17.581078,0,50.0,56.685894,10.4,0,29.1,Low
2,2023-12-12,Credit Reporting Or Other Personal Consumer Re...,Credit reporting,Problem with a company's investigation into an...,Their investigation did not fix an error on yo...,I am formally requesting this letter to update...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",FL,NaN,Closed with non-monetary relief,...,2023-12-12,43.437290,15.498077,0,50.0,56.371264,11.4,0,24.3,Low
3,2024-01-18,Credit Reporting Or Other Personal Consumer Re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,This is my first endeavor to tell you that I a...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",NaN,NaN,Closed with non-monetary relief,...,2024-01-18,16.990128,22.314984,0,50.0,58.311484,20.6,100,45.6,Medium
4,2023-12-15,Credit Card,General-purpose credit card or charge card,Problem with a company's investigation into an...,Was not notified of investigation status or re...,Take a look at the attached documents. I reque...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",IL,NaN,Closed with non-monetary relief,...,2023-12-15,60.459203,17.581078,0,50.0,56.528579,6.4,0,28.6,Low

In [19]:
p.priority_tier.unique()

<ArrowStringArray>
['Medium', 'Low', 'High', 'Critical']
Length: 4, dtype: str

In [21]:
p.category.unique()

<ArrowStringArray>
['Credit Reporting',      'Credit Card',  'Debt Collection',
        'Auto Loan',     'Bank Account',   'Money Transfer',
    'Personal Loan',     'Student Loan',         'Mortgage',
     'Prepaid Card']
Length: 10, dtype: str

In [17]:
p.Issue.unique()

<ArrowStringArray>
[                                                     'Improper use of your report',
                  'Problem with a company's investigation into an existing problem',
                                             'Incorrect information on your report',
                                 'Unable to get your credit report or credit score',
                                    'Problem with fraud alerts or security freezes',
                                                'Attempts to collect debt not owed',
 'Problem with a credit reporting company's investigation into an existing problem',
                                                  'Written notification about debt',
                    'Problem with a company's investigation into an existing issue',
                                                        'Electronic communications',
                          'Credit monitoring or identity theft protection services',
                                                            'Getting a credit card',
                              'Took or threatened to take negative or legal action',
                                                          'Getting a loan or lease',
                    'Threatened to contact someone or share information improperly',
                           'Identity theft protection or other monitoring services',
                                               'False statements or representation',
                                                              'Managing an account',
                                                                    'Fraud or scam',
                              'Problem with additional add-on products or services',
                                                     'Problem when making payments',
                                                             'Closing your account',
                                                 'Confusing or missing disclosures',
                                                       'Managing the loan or lease',
                                                            'Communication tactics',
                                                    'Problem with customer service',
                                                               'Opening an account',
                                                                     'Repossession',
                          'Advertising and marketing, including promotional offers',
                                             'Received a loan you didn't apply for',
                                                         'Getting a line of credit',
                                                         'Unexpected or other fees',
                                 'Confusing or misleading advertising or marketing',
                                                   'Trouble during payment process',
                                                 'Didn't provide services promised',
                                                               'Closing an account',
                                             'Dealing with your lender or servicer',
                                  'Problem with a purchase shown on your statement',
                                                                 'Fees or interest',
                                               'Other features, terms, or problems',
                     'Problem with a lender or other company charging your account',
                                                        'Other transaction problem',
                                       'Charged fees or interest you didn't expect',
                                                    'Struggling to repay your loan',
                                                                   'Getting a loan',
                                                       'Struggling to pay mortgage',
                                               'Charged upfront or unexpected fees',
                                                      'Struggling to pay your loan',
                                              'Unauthorized withdrawals or charges',
                                                                 'Getting the loan',
                                           'Problem caused by your funds being low',
                                     'Loan payment wasn't credited to your account',
                                                             'Credit limit changed',
                           'Unauthorized transactions or other transaction problem',
                      'Applying for a mortgage or refinancing an existing mortgage',
                                                            'Closing on a mortgage',
                                                          'Trouble using your card',
                                         'Problems at the end of the loan or lease',
                           'Problem with the payoff process at the end of the loan',
                                                      'Struggling to pay your bill',
                                                                      'Advertising',
                                              'Problem with a purchase or transfer']
Length: 62, dtype: str

In [12]:
p.bert_topic_label.unique()

<ArrowStringArray>
[                                                nan,
          'credit | report | information | consumer',
                                           'Outlier',
 'deficient | physically | allegations | challenged',
            'unseen | stolen | resilience | harmony',
               'therefore | proof | debt | supplied',
                  'made | perjury | declare | being',
                 'alert | fraud | alerts | extended',
          'definitely | exactly | doesnt | personal',
       'inquiries | inquiry | purpose | permissible',
        'insights | invaluable | expertise | moment',
        'lender | specified | inquiry | communicate',
                        'opened | name | llc | date',
           'suspicious | ignore | amend | mentioned',
            'after | bureau | continuing | disputes',
        'respond | negatively | submitting | failed',
      'errors | incomplete | furnishers | originate',
           'includes | relevant | details | profile',
               'relate | done | does | transactions',
            'contract | payment | imposition | made',
               'ridiculous | always | paid | update']
Length: 21, dtype: str

In [8]:
p.Issue.unique()

<ArrowStringArray>
[                                                     'Improper use of your report',
                  'Problem with a company's investigation into an existing problem',
                                             'Incorrect information on your report',
                                 'Unable to get your credit report or credit score',
                                    'Problem with fraud alerts or security freezes',
                                                'Attempts to collect debt not owed',
 'Problem with a credit reporting company's investigation into an existing problem',
                                                  'Written notification about debt',
                    'Problem with a company's investigation into an existing issue',
                                                        'Electronic communications',
                          'Credit monitoring or identity theft protection services',
                                                            'Getting a credit card',
                              'Took or threatened to take negative or legal action',
                                                          'Getting a loan or lease',
                    'Threatened to contact someone or share information improperly',
                           'Identity theft protection or other monitoring services',
                                               'False statements or representation',
                                                              'Managing an account',
                                                                    'Fraud or scam',
                              'Problem with additional add-on products or services',
                                                     'Problem when making payments',
                                                             'Closing your account',
                                                 'Confusing or missing disclosures',
                                                       'Managing the loan or lease',
                                                            'Communication tactics',
                                                    'Problem with customer service',
                                                               'Opening an account',
                                                                     'Repossession',
                          'Advertising and marketing, including promotional offers',
                                             'Received a loan you didn't apply for',
                                                         'Getting a line of credit',
                                                         'Unexpected or other fees',
                                 'Confusing or misleading advertising or marketing',
                                                   'Trouble during payment process',
                                                 'Didn't provide services promised',
                                                               'Closing an account',
                                             'Dealing with your lender or servicer',
                                  'Problem with a purchase shown on your statement',
                                                                 'Fees or interest',
                                               'Other features, terms, or problems',
                     'Problem with a lender or other company charging your account',
                                                        'Other transaction problem',
                                       'Charged fees or interest you didn't expect',
                                                    'Struggling to repay your loan',
                                                                   'Getting a loan',
                                                       'Struggling to pay mortgage',
                                               'Charged upfront or unexpected fees',
                                                      'Struggling to pay your loan',
                                              'Unauthorized withdrawals or charges',
                                                                 'Getting the loan',
                                           'Problem caused by your funds being low',
                                     'Loan payment wasn't credited to your account',
                                                             'Credit limit changed',
                           'Unauthorized transactions or other transaction problem',
                      'Applying for a mortgage or refinancing an existing mortgage',
                                                            'Closing on a mortgage',
                                                          'Trouble using your card',
                                         'Problems at the end of the loan or lease',
                           'Problem with the payoff process at the end of the loan',
                                                      'Struggling to pay your bill',
                                                                      'Advertising',
                                              'Problem with a purchase or transfer']
Length: 62, dtype: str

In [4]:
p = pd.read_csv("data/clipped.csv")
p.columns

Index(['Unnamed: 0', 'Date received', 'Product', 'Sub-product', 'Issue',
       'Sub-issue', 'Consumer complaint narrative', 'Company public response',
       'Company', 'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='str')

In [2]:
fm.covert_to_parquet('data/complaints_labeled.csv', 'labeled_complaints')

Converting data/complaints_labeled.csv to data/labeled_complaints.parquet...
Conversion complete! You can now use data/data.parquet in your chatbot.

In [26]:
import duckdb
result = duckdb.sql("""
    SELECT "category", "priority_tier", COUNT(*) AS cnt
    FROM 'data/labeled/*.parquet'
    WHERE "category" IS NOT NULL AND "priority_tier" IS NOT NULL
    GROUP BY "category", "priority_tier"
    QUALIFY ROW_NUMBER() OVER (PARTITION BY "category" ORDER BY cnt DESC) = 1
    ORDER BY "category"
""").fetchdf()
for _, row in result.iterrows():
    print(f'    "{row["category"]}": "{row["priority_tier"]}",')

    "Auto Loan": "Medium",
    "Bank Account": "Medium",
    "Credit Card": "Low",
    "Credit Reporting": "Medium",
    "Debt Collection": "Low",
    "Money Transfer": "Medium",
    "Mortgage": "Medium",
    "Personal Loan": "Medium",
    "Prepaid Card": "Medium",
    "Student Loan": "Low",

In [5]:
load_dotenv()

True

In [3]:
import pandas as pd
df = pd.read_parquet('data/recording_20260419_185826.parquet')
print(df.head())

                        Consumer complaint narrative  Company  \
0  He stole all my money and they also gave me a ...  Unknown

        Date received State
0 2026-04-19 18:58:26    MN

In [2]:
file_path = "data/data.parquet"
csv_file = "data/complaints.csv"

if not os.path.exists(file_path):
    fm.covert_to_parquet(csv_file)

Converting data/complaints.csv to data.parquet...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Conversion complete! You can now use data.parquet in your chatbot.

In [ ]:


def transcribe_and_append(audio_path, csv_path, target_column, model=None):
    """
    Transcribes an audio file and appends the result to a specific column in a CSV.
    
    Parameters:
    - audio_path (str): Path to the audio file (e.g., .mp3, .wav).
    - csv_path (str): Path to the CSV file.
    - target_column (str): The name of the column where the text should be stored.
    - model (WhisperModel, optional): A pre-loaded faster-whisper model object.
    """
    
    # 1. Load the model if one wasn't passed in
    # (Using large-v3-turbo and float16 optimized for your hardware)
    if model is None:
        print("Loading Whisper model into VRAM...")
        model = WhisperModel("large-v3-turbo", device="cuda", compute_type="float16")

    # 2. Transcribe the audio
    print(f"Transcribing '{os.path.basename(audio_path)}'...")
    segments, info = model.transcribe(audio_path, beam_size=5)

    # Combine the generator segments into a single continuous string
    transcription = " ".join([segment.text for segment in segments]).strip()
    print(f"Transcription complete. Length: {len(transcription)} characters.")

    # 3. Handle the CSV updating
    file_exists = os.path.isfile(csv_path)
    
    if file_exists:
        df = pd.read_csv(csv_path)
    else:
        # If the file doesn't exist, initialize an empty DataFrame
        df = pd.DataFrame()

    # Create a new row of data. 
    # Adding the filename as an ID is best practice so you know which audio it came from.
    new_row_data = {
        # "Audio_File": os.path.basename(audio_path), 
        target_column: transcription
    }
    
    # Convert the new row into a DataFrame and concatenate it
    new_row_df = pd.DataFrame([new_row_data])
    df = pd.concat([df, new_row_df], ignore_index=True)

    # Save the updated DataFrame back to the CSV
    df.to_csv(csv_path, index=False)
    print(f"Successfully appended data to '{csv_path}'.\n")
    
    return transcription

In [4]:
df1 = pd.read_csv('clipped.csv')
df1.columns

Index(['Unnamed: 0', 'Date received', 'Product', 'Sub-product', 'Issue',
       'Sub-issue', 'Consumer complaint narrative', 'Company public response',
       'Company', 'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='str')

In [5]:
df1.head()

,Unnamed: 0,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,0.0,2020-07-06,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,FL,346XX,NaN,Other,Web,2020-07-06,Closed with explanation,Yes,NaN,3730948.0
1,1.0,2019-12-26,Credit card or prepaid card,General-purpose credit card or charge card,"Advertising and marketing, including promotion...",Confusing or misleading advertising about the ...,NaN,NaN,CAPITAL ONE FINANCIAL CORPORATION,CA,94025,NaN,Consent not provided,Web,2019-12-26,Closed with explanation,Yes,NaN,3477549.0
2,2.0,2020-05-08,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,These are not my accounts.,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,NV,89030,NaN,Consent provided,Web,2020-05-08,Closed with explanation,Yes,NaN,3642453.0
3,3.0,2024-01-05,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,Kindly address this issue on my credit report....,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,IL,60502,NaN,Consent provided,Web,2024-01-05,Closed with non-monetary relief,Yes,NaN,8113747.0
4,4.0,2024-01-21,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,NC,27401,Servicemember,Consent not provided,Web,2024-01-21,Closed with explanation,Yes,NaN,8191825.0

In [1]:

# This disables the symlink behavior entirely
# os.environ["HF_HUB_DISABLE_SYMLINKS"] = "1"
os.environ["HF_TOKEN"] = os.getenv("WHISP_KEY")

# 2. Transcribe the audio
# model = WhisperModel("large-v3-turbo", device="cpu", compute_type="int8") # using cpu here
model = WhisperModel("large-v3-turbo", device="cuda", compute_type="float16") # gpu
audio_path = 'sample.m4a'
print(f"Transcribing '{os.path.basename(audio_path)}'...")
segments, info = model.transcribe(audio_path, beam_size=5)

# Combine the generator segments into a single continuous string
transcription = " ".join([segment.text for segment in segments]).strip()
print(f"Transcription complete. Length: {len(transcription)} characters.")

print(transcription)

NameError: name 'os' is not defined

In [2]:
# ==========================================
# Example Usage:
# ==========================================

os.environ["HF_TOKEN"] = os.getenv("WHISP_KEY")

# Load the model ONCE outside the function to save time on multiple files
my_model = WhisperModel("large-v3-turbo", device="cpu", compute_type="int8") # using cpu here

# Run the function
fm.transcribe(
    audio_path="sample.m4a"
)

Loading Whisper model into VRAM...
Transcribing 'sample.m4a'...
Transcription complete. Length: 45 characters.

'Can you please close my bank account? Please.'

In [62]:
# removing appended
df = pd.read_csv('clipped.csv')

In [59]:
df = df[:-1]

In [63]:

print(df.iloc[-1])

Unnamed: 0                                                              NaN
Date received                                                           NaN
Product                                                                 NaN
Sub-product                                                             NaN
Issue                                                                   NaN
Sub-issue                                                               NaN
Consumer complaint narrative    My money was stolen. Give me my money back.
Company public response                                                 NaN
Company                                                                 NaN
State                                                                   NaN
ZIP code                                                                NaN
Tags                                                                    NaN
Consumer consent provided?                                              NaN
Submitted via                                                           NaN
Date sent to company                                                    NaN
Company response to consumer                                            NaN
Timely response?                                                        NaN
Consumer disputed?                                                      NaN
Complaint ID                                                            NaN
Name: 1014, dtype: object

In [ ]:
PATH="/mnt/c/Users/Raja/Documents/Sound Recordings" 
files = fm.get_existing_files(PATH)

while True:
    
    result = fm.check_for_new_file(PATH, files)

    if result:
        print(f'New File {result[0]} found')

        transcribe_and_append(
            audio_path=result[0],
            csv_path="clipped.csv",
            target_column="Consumer complaint narrative",
        )
        time.sleep(3)
        files = fm.get_existing_files(PATH)

    time.sleep(5)
    print('No new file found')

No new file found
No new file found
New File /mnt/c/Users/Raja/Documents/Sound Recordings/Recording (5).m4a found
Loading Whisper model into VRAM...
Transcribing 'Recording (5).m4a'...
Transcription complete. Length: 43 characters.
Successfully appended data to 'clipped.csv'.

No new file found

KeyboardInterrupt: